services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf"]
    networks:
      - codesnap-network

  postgres-keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    networks:
      - codesnap-network

  postgres-users:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    networks:
      - codesnap-network

  postgres-exercises:
    image: postgres:15
    environment:
      POSTGRES_DB: exercises_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-exercises-data:/var/lib/postgresql/data
    networks:
      - codesnap-network

  postgres-attempts:
    image: postgres:15
    environment:
      POSTGRES_DB: attempts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-attempts-data:/var/lib/postgresql/data
    networks:
      - codesnap-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    command: start-dev --import-realm
    depends_on:
      - postgres-keycloak
    networks:
      - codesnap-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - codesnap-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - codesnap-network

volumes:
  postgres-users-data:
  postgres-exercises-data:
  postgres-attempts-data:
  postgres-keycloak-data:
  prometheus-data:
  grafana-data:

networks:
  codesnap-network:
    name: shared-codesnap-network
    driver: bridge