global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codesnap-monitor'

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']
    metrics_path: '/metrics'

  - job_name: 'exercise-service'
    static_configs:
      - targets: ['exercise-service:8000']
    metrics_path: '/metrics'

  - job_name: 'attempt-service'
    static_configs:
      - targets: ['attempt-service:8000']
    metrics_path: '/metrics'

  - job_name: 'code-execution-service'
    static_configs:
      - targets: ['code-execution-service:8000']
    metrics_path: '/metrics'

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8000']
    metrics_path: '/metrics'
