apiVersion: v1
kind: Service
metadata:
  name: grafana-monitoring-bridge
  namespace: default
spec:
  type: ExternalName
  externalName: prom-stack-grafana.monitoring.svc.cluster.local
  ports:
    - port: 80
      targetPort: 3000
