apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codesnap-infrastructure
  namespace: argocd
spec:
  project: codesnap
  source:
    repoURL: https://github.com/RoanKessels072/codesnap-infrastructure.git
    targetRevision: main
    path: k8s/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
